#!/usr/bin/env bash
# script that will display information about subdomains


subs=("www" "lb-01" "web-01" "web-02")


# function that print the information about a domain.
print_info() {
	echo "The subdomain $1 is a $2 record and points to $3"
}


if [ -z "$2" ];
then
	for sub in "${subs[@]}";
	do 
		url="$sub"."$1"
		info=$(dig $url | grep -A1 'ANSWER SECTION:' | awk 'NR > 1 {print}')
		record=$(echo "$info" | awk '{print $4}')
		dest=$(echo "$info" | awk '{print $5}')
		print_info "$sub" "$record" "$dest"
	done

else
	url="$2"."$1"
	info=$(dig $url | grep -A1 'ANSWER SECTION:' | awk 'NR > 1 {print}')
	record=$(echo "$info" | awk '{print $4}')
	dest=$(echo "$info" | awk '{print $5}')

	print_info "$2" "$record" "$dest"

fi
