#!/usr/bin/env bash
# a script to Install nginx and configure it.

apt-get -y update
apt-get -y install nginx

mkdir -p /var/www/html
sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 755 /var/www
echo "Hello World!" >> /var/www/html/index.html
sudo service nginx start
