#!/usr/bin/env bash
# configure NGIX to redirecting /redirect_me to another page


echo "server {
	server_name _;
	llisten 80;
	location /redirect_me {
		return 301 https://example.org;
	}
}" > /etc/nginx/sites-available/default
service nginx restart
