#!/usr/bin/env bash
# configure NGIX to redirecting /redirect_me to another page

apt-get -y update
apt-get -y install nginx

mkdir -p /var/www/html
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
echo "Hello World!" >> /var/www/html/index.html
sudo service nginx start
echo "server {
	server_name _;
	llisten 80;
	root /var/www/html;
	
	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files $uri $uri/ =404;
	}
	
	location /redirect_me {
		return 301 https://example.org;
	}
}" > /etc/nginx/sites-available/default
service nginx restart
