#!/usr/bin/env bash
# configure NGIX to redirecting /redirect_me to another page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
sudo rm /var/www/html/*
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/error-404.html;

path="/etc/nginx/sites-enabled/default"
string_to_replace="# pass PHP scripts to FastCGI serve"
new_string="location \/redirect_me \{\n\t\treturn 301 \$scheme:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t\}\n\t# pass PHP scripts to FastCGI server"
sed -i "s/$string_to_replace/$new_string/" "$path"

new_string="error_page 404 \/error-404.html;\n\t# pass PHP scripts to FastCGI server"
string_to_replace="# pass PHP scripts to FastCGI server";
path="/etc/nginx/sites-enabled/default";
sed -i "s/$string_to_replace/$new_string/" "$path";

service nginx restart
