#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header

sudo apt-get -y update
sudo apt-get -y install nginx

SERVER_HOSTNAME=$(hostname)

echo "
server {
  listen 80 default_server;
  server_name ${SERVER_HOSTNAME};

  # Add your existing website configuration here

  location / {
    # Existing website configuration goes here
    add_header X-Served-By ${SERVER_HOSTNAME};
  }
}
" > /etc/nginx/sites-available/default

# Link the new configuration to be active
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

sudo service nginx restart
