#!/usr/bin/env bash
# script to install and configure HAproxy

sudo apt-get -y install --no-install-recommends software-properties-common;
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4;
sudo apt-get -y install haproxy=2.4.\*;

sudo chown -R "$USER":"$USER" /etc/default/haproxy
sudo chown -R "$USER":"$USER" /etc/haproxy/haproxy.cfg

#init_file="/etc/default/haproxy"
#conf_file="/etc/haproxy/haproxy.cfg"

# configure init script

#string_to_replace="#EXTRAOPTS=\"-de -m 16\""
#new_string="#EXTRAOPTS=\"-de -m 16\"\nENABLED=1"
#sudo sed -i "s/$string_to_replace/$new_string/" "$init_file";

echo "ENABLED=1" > /etc/default/haproxy


# configre backend & frontend

echo "frontend app
	bind *:80
	default_backend web-servers
	" >> /etc/haproxy/haproxy.cfg

echo "backend web-servers
	balance roundrobin
	server 364711-web-01 54.152.186.165:80 check
	server 364711-web-02 34.204.81.233:80 check
	" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
