#!/usr/bin/env bash
# this script displays Best School 10 times
count=1
while [ $count -lt 10 ]
do
	count=$((count + 1))
	if [ $count -eq 4 ]
	then
		echo "bad luck"
	elif [ $count -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
