#!/usr/bin/env bash
# this script displays Best School 20 times
count=0
while [ $count -lt 20 ]
do
	count=$((count + 1))
	echo "$count"
	
	case "$count" in
		4)
		echo "bad luck from China"
		;;
		9)
		echo "bad luck from Japan"
		;;
		17)
		echo "bad luck from Italy"
		;;
	esac
done
