#!/usr/bin/env bash
# Bash script that displays The content of the current directory
# in a list format Where only the part of the name after the first dash is displayed

filename=$(find *-* | cut -d - -f 2,3)

for var in $filename
do
	echo "$var"
done
