#!/usr/bin/env bash
# script that gives you information about the file


if [ -f school ] || [ -d school ]
then
	echo "school file exists"
	status=$(file school)
	
	if [[ ${status:7:8} == "e" ]]
	then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi

	if [[ $(test -f school; echo $?) -eq 0 ]]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
