#!/usr/bin/env bash
# Bash script that displays The content of the current directory
# in a list format Where only the part of the name after the first dash is displayed


files=$(ls | grep [a-z])

for name in $files
do
	if [[ "${name:0:1}" =~ [0-9] ]]
	then
		echo "$name" | cut -d '-' -f 2,3
	else
		echo "$name"
	
	fi
done
